# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "realworld-frontend.name" . }}
    chart: {{ template "realworld-frontend.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ include "realworld-frontend.fullname" . }}
spec:
  type: ClusterIP
  clusterIp:
  ports:
    - name: realworld-frontend
      port: {{ index .Values "service" "port" }}
  selector:
    app: {{ template "realworld-frontend.name" . }}
    release: {{ .Release.Name }}
