{{- if .Values.mongodb.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "realworld-backend.name" . }}
    chart: {{ template "realworld-backend.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "realworld-backend.dbSecret" . }}
type: Opaque
data:
{{- $dbConfig := index .Values "realworld-backend" "dbConfig" }}
  username: {{ $dbConfig.username | b64enc }}
  password: {{ $dbConfig.password | b64enc }}
{{- end -}}
